# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_faceext', [dirname(__file__)])
        except ImportError:
            import _faceext
            return _faceext
        if fp is not None:
            try:
                _mod = imp.load_module('_faceext', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _faceext = swig_import_helper()
    del swig_import_helper
else:
    import _faceext
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Feature(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Feature, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Feature, name)
    __repr__ = _swig_repr
    __swig_setmethods__["isRec"] = _faceext.Feature_isRec_set
    __swig_getmethods__["isRec"] = _faceext.Feature_isRec_get
    if _newclass:
        isRec = _swig_property(_faceext.Feature_isRec_get, _faceext.Feature_isRec_set)
    __swig_setmethods__["data"] = _faceext.Feature_data_set
    __swig_getmethods__["data"] = _faceext.Feature_data_get
    if _newclass:
        data = _swig_property(_faceext.Feature_data_get, _faceext.Feature_data_set)

    def __init__(self):
        this = _faceext.new_Feature()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _faceext.delete_Feature
    __del__ = lambda self: None
Feature_swigregister = _faceext.Feature_swigregister
Feature_swigregister(Feature)

class Faceext(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Faceext, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Faceext, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _faceext.new_Faceext()
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def init(self):
        return _faceext.Faceext_init(self)

    def getFeatures(self, arg2):
        return _faceext.Faceext_getFeatures(self, arg2)

    def CalSimilar(self, arg2, arg3):
        return _faceext.Faceext_CalSimilar(self, arg2, arg3)
    __swig_setmethods__["FD"] = _faceext.Faceext_FD_set
    __swig_getmethods__["FD"] = _faceext.Faceext_FD_get
    if _newclass:
        FD = _swig_property(_faceext.Faceext_FD_get, _faceext.Faceext_FD_set)
    __swig_setmethods__["FL"] = _faceext.Faceext_FL_set
    __swig_getmethods__["FL"] = _faceext.Faceext_FL_get
    if _newclass:
        FL = _swig_property(_faceext.Faceext_FL_get, _faceext.Faceext_FL_set)
    __swig_setmethods__["FR"] = _faceext.Faceext_FR_set
    __swig_getmethods__["FR"] = _faceext.Faceext_FR_get
    if _newclass:
        FR = _swig_property(_faceext.Faceext_FR_get, _faceext.Faceext_FR_set)
    __swig_destroy__ = _faceext.delete_Faceext
    __del__ = lambda self: None
Faceext_swigregister = _faceext.Faceext_swigregister
Faceext_swigregister(Faceext)

# This file is compatible with both classic and new-style classes.


